/*
* Configuration of module: OsekOs (userapp.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12_XE
*
* Module vendor:           iSoft
* Generator version:       2.0.11
*
* Generated by iSoft Shanghai Software Lab 
*           on Mon May 13 17:21:55 CST 2013
*/

#include "Os.h"
#include "Platform_Types.h"
#include "Sci.h"
#include "TestCtrl.h"

/*TASK...*/

TASK(Task3)/*Task3:Type = BASIC Priority = 0*/
{
/*Please insert your code here...*/

	//putdata(0x3a);
	Test_Main();	
	
	TerminateTask();
}


TASK(Task1)/*Task1:Type = BASIC Priority = 1*/
{
/*Please insert your code here...*/
	
	Sci_Init();

	TerminateTask();
}


TASK(Task2)/*Task2:Type = BASIC Priority = 1*/
{
/*Please insert your code here...*/

    //Put_String("Task2 is running\n");
    //putdata(0x3a);
	TerminateTask();
}


/*AlarmCallBack...*/