/*
* Configuration of module: OsekOs (cfgobj.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12_XE
*
* Module vendor:           iSoft
* Generator version:       2.0.11
*
* Generated by iSoft Shanghai Software Lab 
*           on Mon May 13 17:21:55 CST 2013
*/

#include "Os.h"
#include "cfgobj.h"

#define osTopOfStack(stack)    ((StackPtrType)((&(stack)[0])+(sizeof(stack)/sizeof((stack)[0]))))
#define osBottomOfStack(stack)  ((StackPtrType)(stack))

/*Task managment*/
#if ((CFG_CC == BCC1)||(CFG_CC == ECC1))
	TaskType osReadyTable[CFG_PRIORITY_MAX];
#else
	TaskType osActivateQueue_0[2];
	TaskType osActivateQueue_1[5];	
	TaskType* const osReadyQueue[CFG_PRIORITY_MAX]={	
		osActivateQueue_0,	
		osActivateQueue_1,	
	};

	SizeType const osActivateQueueSize[CFG_PRIORITY_MAX] = {	
		2,			
		5,		
	};
	
	Queue osReadyQueueMark[CFG_PRIORITY_MAX];
#endif

/*Stack management*/
StackDataType osSystemStack_0[1000];
StackDataType osTaskStack_0[100];
StackDataType osTaskStack_1[100];
StackDataType osTaskStack_2[100];

StackType const osSystemStack = {osTopOfStack(osSystemStack_0), osBottomOfStack(osSystemStack_0)};

#if (CFG_TASK_STACK_MAX>0)
	StackType const osTaskStack[CFG_TASK_STACK_MAX]={
		{osTopOfStack(osTaskStack_0), osBottomOfStack(osTaskStack_0)},
		{osTopOfStack(osTaskStack_1), osBottomOfStack(osTaskStack_1)},
		{osTopOfStack(osTaskStack_2), osBottomOfStack(osTaskStack_2)},
	};
#endif

/*Task management*/
#if (CFG_TASK_MAX>0)
	TaskInfo const osTask[CFG_TASK_MAX]={	
		{OSEK_TASK_Task3, Task3, 0, 1, 0},	
		{OSEK_TASK_Task1, Task1, 1, 1, 1},	
		{OSEK_TASK_Task2, Task2, 1, 1, 2},		
	};  /* tasks static infomation module*/

	#if (CFG_SCHEDULE == PREEMPTIVE_MIXED)
		ScheduleType const osTaskSchedule[CFG_TASK_MAX] = {		
			PREEMPTIVE_FULL,		
			PREEMPTIVE_FULL,		
			PREEMPTIVE_FULL,
		};
	#endif
	
	#if (CFG_INTERNAL_RESOURCE_MAX>0)
		PriorityType const osTaskCeiling[CFG_TASK_MAX] = {		
			0,		
			0,		
			0,		
		};
	#endif
	
	AppModeType const osTaskAutoStartMask[CFG_TASK_MAX] = {	
		(NULL_APPMODE),	
		(AppMode),	
		(NULL_APPMODE),		
	};
#endif


/*Resource management*/
#if(CFG_STD_RESOURCE_MAX>0)
	ResourceInfo const osResource[CFG_STD_RESOURCE_MAX] = {	
		{1},	
		{1},		
	};
#endif


/*Counter management*/
#if (CFG_COUNTER_MAX > 0)
CounterInfo const osCounter[CFG_COUNTER_MAX]={
	{{OSMAXALLOWEDVALUE_couter , OSTICKSPERBASE_couter , OSMINCYCLE_couter} ,OSMAXALLOWEDVALUE_couter*2+1},
};

void system_timer(void)
{
	IncrementCounter(couter);	
}
#endif

/*Alarm Callback Declaration*/
void AlarmCallback_OsekOsAlarm2(void){
	ActivateTask(Task3);	
}
void AlarmCallback_OsekOsAlarm1(void){
	ActivateTask(Task2);	
}

#if (CFG_ALARM_MAX>0)
	AlarmInfo const osAlarm[CFG_ALARM_MAX]={	
		{couter,AlarmCallback_OsekOsAlarm2},	
		{couter,AlarmCallback_OsekOsAlarm1},		
	};
#endif


/*Alarm autostart-Appmode Declaration*/
#if (CFG_AUTO_ALARM_MAX>0)
	AlarmAutostartType const osAlarmAutoStart[CFG_AUTO_ALARM_MAX] = {	
		{AppMode,100,10},	
		{AppMode,100,5},
	};
#endif


#if (CFG_TASK_MAX>0)
	TCB osTcb[CFG_TASK_MAX];
#endif
#if (CFG_EXTENDED_TASK_MAX>0)
	EventMaskType osTaskEvent[CFG_EXTENDED_TASK_MAX];
	EventMaskType osTaskWaitEvent[CFG_EXTENDED_TASK_MAX];
#endif
#if (CFG_STD_RESOURCE_MAX>0)
	ResourceCB osResourceCB[CFG_STD_RESOURCE_MAX];
#endif
#if (CFG_COUNTER_MAX>0)
	CounterCB osCounterCB[CFG_COUNTER_MAX];
#endif
#if (CFG_ALARM_MAX>0)
	AlarmCB osAlarmCB[CFG_ALARM_MAX];
#endif

