/*
* Configuration of module: OsekOs (config.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    HCS12_XE
*
* Module vendor:           iSoft
* Generator version:       2.0.11
*
* Generated by iSoft Shanghai Software Lab 
*           on Mon May 13 17:21:55 CST 2013
*/

#ifndef _CONFIG_H
#define _CONFIG_H

#include "option.h"

#define CFG_CC ECC2

#define CFG_STATUS STATUS_STANDARD

#define CFG_SCHEDULE PREEMPTIVE_MIXED

#define CFG_PRIORITY_MAX 2
#define CFG_TASK_STACK_MAX 3
#define CFG_TASK_MAX 3
#define CFG_EXTENDED_TASK_MAX 0

#define CFG_COUNTER_MAX 1
#define CFG_ALARM_MAX 2
#define CFG_AUTO_ALARM_MAX 2

#define CFG_ISR2_IPL_MAX 0
#define INT_NEST_ENABLE FALSE

#define CFG_RESOURCE_MAX 2
#define CFG_STD_RESOURCE_MAX 2
#define CFG_INTERNAL_RESOURCE_MAX (CFG_RESOURCE_MAX - CFG_STD_RESOURCE_MAX)

/* task definition */
#define Task3 ((TaskType)0)
#define Task1 ((TaskType)1)
#define Task2 ((TaskType)2)

/* resource definition */
#define RES_SCHEDULER ((ResourceType) 0)
#define Resource1 ((ResourceType) 1)

/*event definition*/
#define Event1 ((EventMaskType) 0x1)

/* system clock config */
#define CPU_FREQUENCY 64        /* cpu frequency in MHZ */
#define TICK_DURATION 1000      /* the duration of ticks of the system in us */
#define DECR_V (TICK_DURATION*CPU_FREQUENCY)  /* the value should be set to DEC and DECAR */

/*counter definition*/
#define couter ((CounterType) 0)

#define OSMAXALLOWEDVALUE_couter ((TickType) 65535)
#define OSTICKSPERBASE_couter ((TickType) 1)
#define OSMINCYCLE_couter ((TickType) 1)


/* alarm definition */
#define OsekOsAlarm2 ((AlarmType) 0)
#define OsekOsAlarm1 ((AlarmType) 1)

/* appmode definition */
#define AppMode ((AppModeType) 0x1)

#define CFG_ERRORHOOK FALSE
#define CFG_PRETASKHOOK FALSE
#define CFG_POSTTASKHOOK FALSE
#define CFG_STARTUPHOOK FALSE
#define CFG_SHUTDOWNHOOK FALSE

#endif
